### ISSUE TITLE
Mythril reproduction

### ISSUE THREAD

**Issue by elizabethdinella** [sujeetc/ScrawlD#1]
Hello, thank you very much for your great work and making your dataset publicly available.

While looking through your dataset, I randomly selected [0x77b3106417d4CF3138882cc21d4710c71183b707](https://etherscan.io/address/0x77b3106417d4cf3138882cc21d4710c71183b707#code)

I am trying to reproduce the mythril output on this sample, but did not have any luck. What version of mythril did you use and what were the flags? (Timeout, max size of sequence, etc)

Thank you!

**Comment by sujeetc** [comment]
Mythril version link: https://github.com/ConsenSys/mythril/tree/05a1b5bb7e09d309a0ca815ead942dfd73f86ce7
Command to run mythril (with timeout):  myth a ${main_contract_file} -o json --execution-timeout 86400

**Comment by elizabethdinella** [comment]
Thank you! Will try with those flags... I was only running for 5min 😅
