### ISSUE TITLE
Line Number Mismatch

### ISSUE THREAD

**Issue by elizabethdinella** [sujeetc/ScrawlD#2]
Hi, 

I am looking at the contract [0x009e864923b49263c7f10d19b7f8ab7a9a5aad33](https://etherscan.io/address/0x009e864923b49263c7f10d19b7f8ab7a9a5aad33#code) and its corresponding mythril output in the ScrawID `results/mythril/ `directory. 

The JSON file `results/mytril/0x009e864923b49263c7f10d19b7f8ab7a9a5aad33_ext_mythril.json` shows an assertion violation  on **line 82** upon calling `approve` and `increaseApproval`. After some debugging, I believe mythril is triggering the assertion on **line 77**: `assert(c >= a);`. To download the source, I used the `ExtFromEtherScan.py` provided. 

What is the source of this 5 line discrepancy? Am I interpreting the lineno mythril outputs incorrectly? Did I download from Etherscan incorrectly? or something else?

**Comment by sujeetc** [comment]
Hi Elizabeth, Thanks for pointing it out.

It's the problem with the Mythril tool. I tried different things with the same contract (deleting the comments, and adding extra spaces).  But every time, Mythril was giving incorrect line numbers for the assertion violation bug. You can try these things yourself and verify.

Please let us know if you need more clarification.

**Comment by elizabethdinella** [comment]
Thank you for investigating this. I had suspected it might be a problem with Mythril..
